# fly.toml app configuration file generated for saas-chatbot-prototype on 2025-09-10T11:49:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'saas-chatbot-prototype'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
